apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgoc-gitops
  description: This is GitOps manifest for testgoc   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgoc
    janus-idp.io/tekton: testgoc 
    backstage.io/kubernetes-id: testgoc 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgoc
