apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgoc
  janus-idp.io/tekton: testgoc
  backstage.io/kubernetes-id: testgoc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgoc
resources:
- deployment.yaml
- route.yaml
- service.yaml
